# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'data:/data'
      - 'certs:/certs'
      - 'minio_data:/minio_data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

volumes:
  data:
    driver: local
  certs:
    driver: local
  minio_data:
    driver: local
